---
# Service
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  selector:
    app: ${APPLICATION_NAME}
  ports:
    - port: 80
    #- port: 8080
      targetPort: ${HTTP_PORT}
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
      - name: ${APPLICATION_NAME}
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        ports:
        - containerPort: ${HTTP_PORT}
        imagePullPolicy: Never # 🤚
        #imagePullPolicy: IfNotPresent
        #imagePullPolicy: Always
        env: # 🤚
        - name: WASM_FILE
          value: "${WASM_FILE}"
        - name: HTTP_PORT
          value: "${HTTP_PORT}"
        - name: FUNCTION_NAME
          value: "${FUNCTION_NAME}"
        - name: WASM_REGISTRY
          value: "${WASM_REGISTRY}"
        - name: WASM_URI
          value: "${WASM_URI}"

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${APPLICATION_NAME}
spec:
  rules:
    - host: ${APPLICATION_NAME}.${DNS} # 🤚
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service: 
              name: ${APPLICATION_NAME}
              port: 
                #number: 8080
                number: 80   
